apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: chaos-app:latest
          imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: main-app

spec:
  selector:
    app: main-app
  ports:
    - port: 80
      targetPort: 80
